//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCLamda.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Department
    {
        public tbl_Department()
        {
            this.tbl_Employee = new HashSet<tbl_Employee>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<double> Salary { get; set; }
    
        public virtual ICollection<tbl_Employee> tbl_Employee { get; set; }
    }
}
