//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCLamda.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Employee
    {
        public int id { get; set; }
        public string Name { get; set; }
        public string Gender { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public Nullable<int> GradeId { get; set; }
        public string Address { get; set; }
       
    
        public virtual tbl_Department tbl_Department { get; set; }
        public virtual tbl_Grade tbl_Grade { get; set; }
    }
}
